onEvent('recipes', event => {
    const nukedRecipes = [
        'tconstruct:smeltery/seared/seared_bricks_crafting',
        'tconstruct:smeltery/seared/seared_bricks_from_brick',
		'tconstruct:smeltery/casting/seared/brick_composite',
        'minecraft:conduit',
        'architects_palette:abyssaline',
        'malum:spirit_altar',
		'minecraft:wooden_sword',
		'minecraft:wooden_hoe',
		'minecraft:wooden_shovel',
		'minecraft:wooden_axe',
		'minecraft:wooden_pickaxe',
		'minecraft:crafting_table',
		'nethers_exoticism:crafting_table_recipe_1',
		'nethers_exoticism:crafting_table_recipe_2',
		'minecraft:campfire',
		'hardcore_torches:lit_torch',
		'minecraft:torch',
		'immersiveengineering:crafting/torch',
		'decorative_blocks:torch_from_chandelier',
		'apotheosis:torch',
		'thermal:saw_blade',
		'minecraft:stonecutter',
		'quark:building/smelting/moss_paste',
		'minecraft:green_bed',
		'tconstruct:smeltery/seared/seared_brick',
		'tconstruct:smeltery/seared/seared_brick_kiln',
		'tconstruct:smeltery/seared/grout',
		'tconstruct:smeltery/seared/grout_multiple',
		'minecraft:lightning_rod',
		'immersiveengineering:crafting/hammer',
		'tconstruct:smeltery/seared/heater',
		'tconstruct:smeltery/seared/melter',
		'quark:building/crafting/furnaces/cobblestone_furnace',
		'quark:building/crafting/furnaces/blackstone_blast_furnace',
		'quark:building/crafting/furnaces/deepslate_blast_furnace',
		'minecraft:blast_furnace',
		'tconstruct:common/basalt_blast_furnace',
		'engineersdecor:independent/small_lab_furnace_recipe',
		'engineersdecor:independent/small_electrical_furnace_recipe',
		'quark:building/crafting/furnaces/deepslate_furnace',
		'quark:building/crafting/furnaces/blackstone_furnace',
		'thermal:furnace_2137139079',
		'tconstruct:compat/create/andesite_alloy_iron',
		'tconstruct:compat/create/andesite_alloy_zinc',
		'architects_palette:algal_blend',
		'create:mixing/andesite_alloy',
		'create:mixing/andesite_alloy_from_zinc',
		'create:crafting/materials/andesite_alloy',
		'create:crafting/materials/andesite_alloy_from_zinc',
		'thermal:compat/create/smelter_create_alloy_andesite_alloy',
		'minecraft:tnt',
		'thermal:rubber_from_vine',
		'thermal:rubber_from_dandelion',
		'thermal:rubber_3',
		'thermal:smelting/cured_rubber_from_smelting',
		'thermal:furnace_778338694'
    ]

    nukedRecipes.forEach((recipeToNuke) => {
        event.remove({id:`${recipeToNuke}`})
    });

	event.remove({id:'botania:apothecary_default'})
	event.remove({id:'botania:apothecary_mossy'})
	event.remove({id:'botania:apothecary_mesa'})
	event.remove({id:'botania:apothecary_taiga'})
	event.remove({id:'botania:apothecary_desert'})
	event.remove({id:'botania:apothecary_swamp'})
	event.remove({id:'botania:apothecary_fungal'})
	event.remove({id:'botania:apothecary_mountain'})
	event.remove({id:'botania:apothecary_plains'})
	event.remove({id:'botania:apothecary_forest'})
	event.remove({id:'malum:hallowed_spirit_resonator'})
	event.remove({id:'aiotbotania:livingwood_sword'})
	event.remove({id:'aiotbotania:livingwood_axe'})
	event.remove({id:'aiotbotania:livingwood_pickaxe'})
	event.remove({id:'aiotbotania:livingwood_shovel'})
	event.remove({id:'aiotbotania:livingwood_hoe'})
	event.remove({id:'aiotbotania:livingwood_aiot'})
	event.remove({id:'aiotbotania:livingwood_shears'})
	event.remove({id:'botania:mana_pool'})
	event.remove({id:'botania:mana_spreader'})
	event.remove({id:'botania:redstone_spreader'})
	event.remove({id:'botania:runic_altar'})
	event.remove({id:'aiotbotania:livingrock_sword'})
	event.remove({id:'aiotbotania:livingrock_axe'})
	event.remove({id:'aiotbotania:livingrock_pickaxe'})
	event.remove({id:'aiotbotania:livingrock_shovel'})
	event.remove({id:'aiotbotania:livingrock_hoe'})
	event.remove({id:'aiotbotania:livingrock_shears'})
	event.remove({id:'aiotbotania:livingrock_aiot'})
	event.remove({id:'botania:manasteel_sword'})
	event.remove({id:'botania:manasteel_axe'})
	event.remove({id:'botania:manasteel_pickaxe'})
	event.remove({id:'botania:manasteel_shovel'})
	event.remove({id:'botania:manasteel_hoe'})
	event.remove({id:'botania:manasteel_shears'})
	event.remove({id:'aiotbotania:manasteel_aiot'})
	event.remove({id:'botania:glimmering_livingwood_log'})
	event.remove({id:'architects_palette:algal_blend'})
    event.remove({input:'tconstruct:grout'})
    event.remove({id:'architects_palette:smelting/algal_brick_from_algal_blend_smelting'})
    event.remove({id:'tconstruct/smeltery/casting/seared/brick_composite'})
    event.remove({id:'create:item_application/andesite_casing_from_log'})
    event.remove({id:'create:item_application/andesite_casing_from_wood'})
    event.remove({id:'create:item_application/brass_casing_from_log'})
    event.remove({id:'create:item_application/brass_casing_from_wood'})
    event.remove({id:'create:item_application/copper_casing_from_log'})
    event.remove({id:'create:item_application/copper_casing_from_wood'})
})