onEvent('worldgen.remove', (event) => {
    event.removeOres((ores) => {
        ores.blocks = [ 
            // Malum
            'malum:blazing_quartz_ore',
            'malum:soulstone_ore',
            'malum:deepslate_soulstone_ore',
            'malum:deepslate_quartz_ore',
            'malum:natural_quartz_ore',
            // Minecraft
            'minecraft:coal_ore',
            'minecraft:deepslate_coal_core',
            'minecraft:iron_ore',
            'minecraft:deepslate_iron_ore',
            'minecraft:copper_ore',
            'minecraft:deepslate_copper_ore',
            'minecraft:gold_ore',
            'minecraft:deepslate_copper_ore',
            'minecraft:redstone_ore',
            'minecraft:deepslate_redstone_ore',
            'minecraft:emerald_ore',
            'minecraft:deepslate_emerald_ore',
            'minecraft:lapis_ore',
            'minecraft:deepslate_lapis_ore',
            'minecraft:diamond_ore',
            'minecraft:deepslate_diamond_ore',
            'minecraft:nether_gold_ore',
            'minecraft:nether_quartz_ore',
            'minecraft:raw_gold_block',
            'minecraft:raw_iron_block',
            'minecraft:raw_copper_block',
            'minecraft:ancient_debris',
            // Immersive Engineering
            'immersiveengineering:deepslate_uranium_ore',
            'immersiveengineering:_uranium_ore',
            'immersiveengineering:deepslate_nickel_ore',
            'immersiveengineering:nickel_ore',
            'immersiveengineering:deepslate_silver_ore',
            'immersiveengineering:silver_ore',
            'immersiveengineering:deepslate_lead_ore',
            'immersiveengineering:lead_ore',
            'immersiveengineering:deepslate_aluminum_ore',
            'immersiveengineering:aluminum_ore',
            // Occultism
            'occultism:silver_ore_deepslate',
            'occultism:silver_ore',
            // Darkerepths
            'darkerdepths:aridrock_gold_ore',
            'darkerdepths:aridrock_iron_ore',
            'darkerdepths:aridrock_coal_ore',
            'darkerdepths:aridrock_lapis_ore',
            'darkerdepths:aridrock_diamond_ore',
            'darkerdepths:aridrock_redstone_ore',
            'darkerdepths:aridrock_silver_ore',
            'darkerdepths:limestone_gold_ore',
            'darkerdepths:limestone_iron_ore',
            'darkerdepths:limestone_coal_ore',
            'darkerdepths:limestone_lapis_ore',
            'darkerdepths:limestone_diamond_ore',
            'darkerdepths:limestone_redstone_ore',
            'darkerdepths:limestone_silver_ore',
            'darkerdepths:silver_ore',
        ];
    });
});
