
# 
#These values affect the extent of cannon failure.
[failure]
	# 
	#Chance that a fired projectile will get stuck in a barrel after exceeding the squib ratio. 0 is 0%, 1 is 100%.
	#Range: 0.0 ~ 1.0
	squibChance = 0.25
	# 
	#Chance that a cannon will fail if a Powder Charge is ignited in a "barrel"-type cannon block. 0 is 0%, 1 is 100%.
	#This chance can be affected by stronger and weaker charge blocks.
	#Range: 0.0 ~ 1.0
	barrelChargeBurstChance = 0.20000000298023224
	# 
	#How strong the explosion of a catastrophic failure is. Scaled by the amount of charges used in the shot.
	#Range: 0.0 ~ 3.4028234663852886E38
	failureExplosionPower = 2.0
	# 
	#Chance that a cannon loaded with more Powder Charges that it can handle will fail. 0 is 0%, 1 is 100%.
	#Range: 0.0 ~ 1.0
	overloadBurstChance = 0.5
	# 
	#Chance that a load with gaps between the loaded Powder Charges will not completely combust. 0 is 0%, 1 is 100%.
	#Range: 0.0 ~ 1.0
	interruptedIgnitionChance = 0.33000001311302185

# 
#These values affect the characteristics of cannon munitions.
[munitions]
	# 
	#If an entity should be invulnerable for a while after being hit by a mod projectile.
	invulnerableAfterProjectileHurt = false
	# 
	#How powerful the High Explosive (HE) shell is. For reference, a block of TNT has an explosion power of 4.
	#Range: 0.0 ~ 3.4028234663852886E38
	heShellPower = 10.0
	# 
	#How powerful the Armor Piercing (AP) shell is. For reference, a block of TNT has an explosion power of 4.
	#Range: 0.0 ~ 3.4028234663852886E38
	apShellPower = 5.0

	# 
	#Projectile Fuzes
	[munitions.fuzes]
		# 
		#Chance that the Impact Fuze will detonate on hitting something. 0 is 0%, 1 is 100%.
		#Range: 0.0 ~ 1.0
		impactFuzeDetonationChance = 0.6700000166893005

	# 
	#Grouped Munitions
	[munitions.groupedMunitions]
		# 
		#Amount of shrapnel bullets that a Shrapnel Shell releases on detonation.
		#Range: > 1
		shrapnelCount = 50
		# 
		#How much shrapnel bullets spread on release.
		#Range: 0.009999999776482582 ~ 3.4028234663852886E38
		shrapnelSpread = 0.25
		# 
		#How much damage a shrapnel bullet does.
		#Range: 0.0 ~ 3.4028234663852886E38
		shrapnelDamage = 10.0
		# 
		#Amount of grapeshot rounds that a Bag of Grapeshot releases.
		#Range: > 1
		grapeshotCount = 25
		# 
		#How much grapeshot rounds spread on release.
		#Range: 0.009999999776482582 ~ 3.4028234663852886E38
		grapeshotSpread = 0.25
		# 
		#How much damage a grapeshot round does.
		#Range: 0.0 ~ 3.4028234663852886E38
		grapeshotDamage = 19.0

# 
#These values affect the characteristics of cannon materials and cannon structures
[cannons]
	# 
	#Maximum length of cannons that can be built.
	#Range: > 3
	maxCannonLength = 64
	# 
	#How much each Powder Charges used affects the spread of a fired projectile.
	#Range: 0.0 ~ 3.4028234663852886E38
	powderChargeSpread = 2.0
	# 
	#How much each cannon barrel reduces the spread of a fired projectile passing through.
	#Range: 0.0 ~ 3.4028234663852886E38
	barrelSpreadReduction = 1.0
	# 
	#Maximum amount of Powder Charges that weak breech blocks can safely handle. Set to -1 to disable this behavior.
	#Range: > -1
	slidingBreechStrength = 4

# 
#These values affect various miscellaneous contraptions.
[kinetics]
	# 
	#Maximum length of cannon loaders that can be built.
	#Range: > 3
	maxLoaderLength = 64

# 
#These values affect cannon crafting properties.
[crafting]
	# 
	#Maximum height of a single cannon cast that can be built.
	#Range: > 1
	maxCannonCastHeight = 32
	# 
	#Maximum length of a Cannon Drill that can be built.
	#Range: > 1
	maxCannonDrillLength = 32
	# 
	#Maximum length of a Cannon Builder that can be built.
	#Range: > 1
	maxCannonBuilderLength = 32
	# 
	#Maximum reach of a Cannon Builder.
	#Range: > 2
	maxCannonBuilderRange = 32
	# 
	#Time a built-up cannon block needs to be heated for until it transforms into its finished form.
	#Range: > 0
	builtUpCannonHeatingTime = 6000

